// Cohort Web UI – API configuration
// Set this to your API Gateway endpoint (Terraform output: approval_api_endpoint base URL)
// e.g. "https://abc123xyz.execute-api.us-east-1.amazonaws.com"
// This file is auto-generated by Terraform with the correct URL.
window.COHORT_API_BASE = "";
